/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'TrustRecord': EventHandler<never, never>
    'TrustEngine': EventHandler<never, { topic: 'trust-updated'; data: never }>
    'SubscriptionValidate': EventHandler<never, { topic: 'subscription-risk-check'; data: never }>
    'SubscriptionRiskCheck': EventHandler<never, { topic: 'subscription-create-payment'; data: never }>
    'SubscriptionRenewalJob': CronHandler<{ topic: 'subscription-validate'; data: never }>
    'SubscriptionPaymentRetry': EventHandler<never, { topic: 'subscription-invoice-generate'; data: never }>
    'SubscriptionInvoiceGenerate': EventHandler<never, { topic: 'subscription-email-send'; data: never }>
    'SubscriptionFinalize': EventHandler<never, never>
    'SubscriptionSendEmail': EventHandler<never, { topic: 'subscription-renewal-finalize'; data: never }>
    'SubscriptionCreatePayment': EventHandler<never, { topic: 'subscription-payment-retry'; data: never }>
    'risk-rescan-job': CronHandler<{ topic: 'risk-eval'; data: never }>
    'risk-eval': EventHandler<never, never>
    'PaymentValidate': EventHandler<never, { topic: 'payment-created'; data: never }>
    'FraudPaymentRiskCheck': EventHandler<never, { topic: 'payment-fraud-check'; data: never }>
    'PaymentReconciliationJobWorker': EventHandler<never, { topic: 'payment-validate'; data: never }>
    'PaymentReconciliationJob': CronHandler<{ topic: 'payment-recon'; data: never }>
    'PaymentInvoice': EventHandler<never, { topic: 'payment-receipt-sent'; data: never }>
    'PaymentCompleted': EventHandler<never, never>
    'PaymentReceiptSent': EventHandler<never, { topic: 'payment-completed'; data: never }>
    'PaymentCreate': EventHandler<never, { topic: 'payment-risk-scanned'; data: never }>
    'PaymentConfirm': EventHandler<never, { topic: 'payment-invoice-generated'; data: never }>
    'DeadLetterRetryJobWorker': EventHandler<never, { topic: 'payment-validate'; data: never }>
    'DeadLetterRetryJob': CronHandler<{ topic: 'dead-letter-retry'; data: never }>
    'OnboardingValidate': EventHandler<never, { topic: 'onboarding-profile-created'; data: never }>
    'OnboardingSendEmail': EventHandler<never, { topic: 'onboarding-completed'; data: never }>
    'OnboardingRiskResult': EventHandler<never, { topic: 'onboarding-email-sent'; data: never }>
    'OnboardingRiskCheck': EventHandler<never, { topic: 'onboarding-risk-result'; data: {} }>
    'OnboardingProfileCreated': EventHandler<never, { topic: 'onboarding-metadata-stored'; data: never }>
    'OnboardingMetadataStored': EventHandler<never, { topic: 'onboarding-risk-check'; data: never }>
    'OnboardingComplete': EventHandler<never, never>
    'ValidateSignupJS': EventHandler<{ userId: string; email: string; name: string }, { topic: 'user-signed-up'; data: {} }>
    'ValidateLoginJS': EventHandler<{}, { topic: 'user-logged-in'; data: {} }>
    'RetryEngine': EventHandler<never, { topic: 'retry-event-execute'; data: never }>
    'AdminDLQList': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DeadLetterQueueHandler': EventHandler<never, { topic: 'retry-needed'; data: never }>
    'AutoUnfreezeLogic': EventHandler<never, never>
    'AdminReprocessTrigger': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'retry-event-execute'; data: never }>
    'PaymentStartApi': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'payment-validate'; data: never } | { topic: 'event.failed'; data: never }>
    'OnboardingStart': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'onboarding-validate'; data: never }>
    'SignupApi': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'validate-signup'; data: { userId: string; email: string; name: string } } | { topic: 'user-signed-up'; data: {} }>
    'AuthMeAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'LoginAPI': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'validate-login'; data: {} } | { topic: 'user-logged-in'; data: {} }>
    'AdminAnalytics': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FraudCheckPython': EventHandler<{}, { topic: 'risk-evaluated'; data: never }>
    'PaymentFraudCheck': EventHandler<never, { topic: 'payment-confirmed'; data: never } | { topic: 'risk-evaluated'; data: never }>
  }
    
}